### PR TITLE
Added Graph Directory and Graph Implementation

### PR DESCRIPTION
**Pull request by imsushant12**
Issue: #3

### CODE REVIEW

**Comment by Ambareen09** [comment]
Kindly provide a question for your code, then it'll be accepted

**Comment by imsushant12** [comment]
Okay

**Comment by imsushant12** [comment]
Please review @Ambareen09

**Comment by Ambareen09** [comment]
LGTM

**Comment by imsushant12** [comment]
> LGTM

Thankyou 🙌

**Pull request merged**
